import Side from "@/components/Sdie";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SpeedInsights } from "@vercel/speed-insights/next";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div className="flex bg-white min-h-screen overflow-y-hidden">
        <Side />
        <div className="bg-[#F2F1EF] rounded-l-3xl w-full p-10 shadow-inner ">
          {children}
          <SpeedInsights />
        </div>
      </div>
    </>
  );
}
